### ISSUE TITLE
Probably a silly question :/

### ISSUE THREAD

**Issue by tombo9999** [botabotlab/ESP32CAM-MQTT#1]
I'm a total beginner about Node-RED, hope you can give me some advice.
Arduino sketch is working properly, no problem.
But if I import your json file from NodeRed-Demo, deploy it and open Node-Red Dashboard the following message appear:
Welcome to the Node-RED Dashboard
Please add some UI nodes to your flow and redeploy.

Thanks in advance, Luca (from Italy)

**Comment by botabotlab** [comment]
Hello, 
you probably forgot to install "node-red-contrib-image-output". 

Go to "manage palette" (top left menu) 
Type "-image" (or node-red-contrib-image-output) 
Then install the new node
![nodered](https://user-images.githubusercontent.com/61827555/81848711-d36b3a00-9555-11ea-839f-654275a1bbd2.png)

**Comment by tombo9999** [comment]
Hi, actually I installed the node.
Just didn't understand how to use your demo (my fault), but now I'm starting to understand a little.
I'm used to node with an UI, but for testing purpose your Demo is more than enough.
Thank you  :)

**Comment by botabotlab** [comment]
Oh no ok it's totally my fault :/ I also have other nodes installed on my flow (NodeRed Dashboard) that are not used fot this demo. And even if I only select and export a few nodes it also exports the whole config. I will create a fresh Flow and update the demo ;)

**Comment by bazok100** [comment]
Hello,
I am also a beginner and I was able to get capturing and publishing working but i need the image for OCR so, I need  reconstruct the image at the subscriber end. I was wondering how to reconstruct the image. All helps appreciated.

Thanks

**Comment by botabotlab** [comment]
Hello,
The ESPCam sends a JPEG buffer you should be able to easily decode/manipulate the image (depending on the software / library you use).
I've added a small OpenCV python demo.

Note : as a biologist, i'm also a beginner in programing my demo might not be perfect and optimized :p but it should at least works.

**Comment by bazok100** [comment]
> Hello,
> The ESPCam sends a JPEG buffer you should be able to easily decode/manipulate the image (depending on the software / library you use).
> I've added a small OpenCV python demo.
> 
> Note : as a biologist, i'm also a beginner in programing my demo might not be perfect and optimized :p but it should at least works.

Oh,thanks for the reply, i will check it out.

Update - I checked it out, it worked fine. I am only wondering to increase the size and quality of the picture captured. What would you recommend?
